channels:
- conda-forge
dependencies:
- python=3.11
- pip<=25.3
- pip:
  - mlflow==2.19.0
  - cloudpickle==3.1.1
  - numpy==2.3.5
  - packaging==24.2
  - pandas==2.3.3
  - psutil==7.0.0
  - pyarrow==18.1.0
  - pyyaml==6.0.3
  - scikit-learn==1.7.2
  - scipy==1.16.3
  - xgboost==3.1.2
name: mlflow-env
